language: ruby
sudo: true
os: linux
dist: trusty
before_script:
  - sudo mkdir /usr/local/aws-cli/
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo chmod -R 777 /usr/local/aws-cli/
  - aws --version
  - ./aws/install
  - rm -rf public
  - bundle exec jekyll build
before_deploy: "echo 'Ready for deploy stage!!!'"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: melissajkipp.com
  acl: public_read
  region: us-west-2
  on:
    branch: main
  local_dir: site/public
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  - "echo 'Deploy Complete!!!'"
