language: ruby
sudo: false
dist: trusty
before_script:
  - pip install --user awscli==1.20.0
  - rm -rf public
  - bundle exec jekyll build
script:
  - aws s3 sync public/ s3://melissajkipp.com --acl public-read --delete
  - aws cloudfront create-invalidation --distribution-id d2pdjq01l8me6x.cloudfront.net --paths '/*'
branches:
  only:
    - main
