language: ruby
rvm:
  - 2.2
  - jruby
services:
  - docker

script:
  - bundle exec jekyll build

after_success:
  - docker build -t melissakipp/melissajkipp:1.0.0 .
  - docker images melissakipp/melissajkipp

branches:
  only:
    - main
