version: "2.7"

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - "4000:4000"
    command: bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000 --trace
